## Colors
if [ ! -z "${SOURCED_COLORS_BASH+x}" ]; then return; fi
SOURCED_COLORS_BASH=true

COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_YELLOW="\e[33m"
COLOR_NORMAL="\e[0m"
COLOR_DEFAULT="\e[39m"
COLOR_BLACK="\e[30m"
COLOR_BLUE="\e[34m"
COLOR_MAGENTA="\e[35m"
COLOR_CYAN="\e[36m"
COLOR_LGRAY="\e[37m"
COLOR_DGRAY="\e[90m"
COLOR_LRED="\e[91m"
COLOR_GREEN="\e[92m"
COLOR_LYELLOW="\e[93m"
COLOR_LBLUE="\e[94m"
COLOR_LMAGENTA="\e[95m"
COLOR_LCYAN="\e[96m"
COLOR_WHITE="\e[97m"


